local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 5.0
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.01
  
  plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer: 
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: top_lrf_link, data_type: LaserScan, topic: /lidar_robot/scan , expected_update_rate: 3.0, marking: true, clearing: true}

  inflation_layer:
    inflation_radius: 0.4