DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 1.0 
  min_vel_theta: -1.0 
  min_in_place_vel_theta: 0.3 
  holonomic_robot: false 
  yaw_goal_tolerance: 0.05 
  xy_goal_tolerance: 0.06 
  path_distance_bias: 0.4
  goal_distance_bias: 0.6
  occdist_scale: 0.0005

  meter_scoring: true